version: "3.2"
services:

  # nacos
  nacos:
    image: nacos/nacos-server:v2.1.1-slim
    container_name: nacos
    restart: always
    environment:
      MODE: standalone
    ports:
      - "8848:8848"

  # mysql
  mysql:
    image: mysql:8.0.31
    container_name: mysql
    restart: always #重启docker引擎后该容器也重启
    environment:
      MYSQL_ROOT_PASSWORD: psikun
    volumes:
      - "~/data/mysql/data:/var/lib/mysql"
      - "~/data/mysql/conf:/etc/mysql/conf.d/"
      - "~/data/mysql/log:/var/log/mysql"
    ports:
      - "3306:3306"

  # redis
  redis:
    image: redis:7.0.7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      #数据和配置挂载
      - "~/data/redis/redis.conf:/usr/local/etc/redis/redis.conf:rw"
      - "~/data/redis/data:/data"
    command: /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf " #使用command可以覆盖容器启动后默认执行的命令。这里启动执行指定的redis.conf文件
